import type { Metadata } from 'next'
import { Inter, JetBrains_Mono } from 'next/font/google'
import './globals.css'

const inter = Inter({
  variable: '--font-sans',
  subsets: ['latin'],
})
const jet = JetBrains_Mono({
  variable: '--font-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'SeisCore',
  description: 'Generated by create next app',
  keywords: ['seismic', 'earthquake', 'monitoring', 'map', 'real-time'],
  openGraph: {
    title: 'SeisCore - Seismic Activity Tracker',
    description:
      'Real-time seismic activity monitoring and visualization platform. Track earthquakes and seismic events on an interactive map.',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${jet.variable} antialiased`}>
        {children}
      </body>
    </html>
  )
}
