import type { Metadata } from 'next'
import { Inter, JetBrains_Mono } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'
import Footer from '@/components/footer'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})
const jet = JetBrains_Mono({
  variable: '--font-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'SeisCore',
  description: 'Generated by create next app',
  keywords: ['seismic', 'earthquake', 'monitoring', 'map', 'real-time'],
  openGraph: {
    title: 'SeisCore - Seismic Activity Tracker',
    description:
      'Real-time seismic activity monitoring and visualization platform. Track earthquakes and seismic events on an interactive map.',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${jet.variable} antialiased font-inter bg-bg-secondary h-screen  flex flex-col`}
      >
        <Header />
        <main className="flex flex-col grow min-h-0">{children}</main>
      </body>
    </html>
  )
}
